[package]
name = "crossterm-test"
version = "0.1.0"
authors = ["pruf"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.24"
rand = "0.8.5"